mv /mnt/scratch/smithlab/arachnid/cds/abrue/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/abrue/protein_isoform/abrue-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/bmori/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/bmori/protein_isoform/bmori-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/crotu/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/crotu/protein_isoform/crotu-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/cscor/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/cscor/protein_isoform/cscor-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/cscul/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/cscul/protein_isoform/cscul-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/dmela/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/dmela/protein_isoform/dmela-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/hlong/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/hlong/protein_isoform/hlong-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/iscap/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/iscap/protein_isoform/iscap-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/lhesp/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/lhesp/protein_isoform/lhesp-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/lpoly/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/lpoly/protein_isoform/lpoly-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/lrecl/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/lrecl/protein_isoform/lrecl-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/mocci/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/mocci/protein_isoform/mocci-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/nclav/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/nclav/protein_isoform/nclav-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/ptepi/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/ptepi/protein_isoform/ptepi-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/smimo/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/smimo/protein_isoform/smimo-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/sscab/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/sscab/protein_isoform/sscab-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/tgiga/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/tgiga/protein_isoform/tgiga-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/turti/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/turti/protein_isoform/turti-longest-isoforms.fa
mv /mnt/scratch/smithlab/arachnid/cds/vdest/protein_isoform/longest-isoforms.fa /mnt/scratch/smithlab/arachnid/cds/vdest/protein_isoform/vdest-longest-isoforms.fa
